# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.20
loader_version=0.19.3
# Mod Properties
mod_version=0.8.6.1-neo1.5.3+mc1.21.11
maven_group=cn.sh1rocu
archives_base_name=touhoulittlemaid-fabric
# Dependencies
fabric_version=0.141.4+1.21.11
jei_version=27.17.0.49
architectury_api_version=19.0.1+fabric
rei_version=21.11.816+fabric
cloth_config_version=21.11.153
jade_version=21.1.6+fabric
carry_on_version=2.2.2-fabric
cca_version=6.1.2
